apiVersion: v1
kind: Pod
metadata:
  name: jumppod
spec:
  containers:
    - name: shell
      image: centos:7
      command: 
        - "bin/bash"
        - "-c"
        - "sleep 10000"
      resources:
        