apiVersion: v1
kind: Pod
metadata:
  name: pod-in-ben-test-namespace
spec:
  containers:
    - name: sise
      image: mhausenblas/simpleservice:0.5.0
      ports:
        - containerPort: 9876
  resources: