apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: shell
      image: centos:7
      command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"
      volumeMounts:
        - name: api-key-vol
          mountPath: "/tmp/apikey"
          readOnly: true
  resource:
  volumes:
    - name: api-key-vol
      secret:
        secretName: apikey