apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod-1
spec:
  containers:
    - name: sise
      image: mhausenblas/simpleservice:0.5.0
      ports:
       - containerPort: 9786
      readinessProbe:
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 9876
      resources:
