apiVersion: v1
kind: Pod
metadata:
  name: labelex2
  labels:
    owner: bensooraj
    env: production
spec:
  containers:
    - name: sise
      image: mhausenblas/simpleservice:0.5.0
      ports:
        - containerPort: 9876
      resources:
